# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # start with an Ubuntu 18.04 box
  config.vm.box = "ubuntu/bionic64"

  # forward ports in the guest's microservices to host ports
  config.vm.network "forwarded_port", guest: 8000, host: 8000 # conductor-service-phr
  config.vm.network "forwarded_port", guest: 8001, host: 8001 # authentication-service-phr
  config.vm.network "forwarded_port", guest: 8002, host: 8002 # mpi-service
  config.vm.network "forwarded_port", guest: 8003, host: 8003 # cdr-service-openehr
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # openid-connect-server

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

  # Sync the local clones of the development repos with the VM filesystem
  config.vm.synced_folder "../../ripple-qewd", "/ripple-qewd"

  config.vm.provision :shell, inline: "sudo apt update"
  config.vm.provision :shell, inline: "sudo apt install -y language-pack-en"
  config.vm.provision :shell, inline: "sudo apt-get install -y --no-install-recommends ubuntu-desktop"
end
