version: '3'

# DOCKER-COMPOSE FILE FOR RIPPLE STACK
# If you don't require all the services you can comment out those you don't need here

services:

  #PULSETILE
  # pulsetile is the react app which is the main Ripple UI
  pulsetile:
    build: ../../ripple-pulsetile # build for local Dockerfile
    volumes:
      - /ripple-pulsetile:/pulsetile/
    ports:
      - "3000:3000"

  # QEWD-MICROSERVICES
  # the conductor-service-phr proxies requests to the correct microservice
  conductor-service-phr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/conductor-service-phr:/opt/qewd/mapped
      - /ripple-qewd/conductor-service-phr/www:/opt/qewd/www
    ports:
      - "8000:8080"

  # the openid-connect-server mimics a CitizenID endpoint
  openid-connect-server:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/openid-connect-server:/opt/qewd/mapped
    ports:
      - "8080:8080"

  # master patient index service
  # enables demographic lookup and identification of ehrId for a patient
  mpi-service:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/mpi-service:/opt/qewd/mapped
    ports:
      - "8002:8080"

  authentication-service-phr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/authentication-service-phr:/opt/qewd/mapped
      - /ripple-qewd/yottadb/authentication:/root/.yottadb/r1.22_x86_64/g
    ports:
      - "8001:8080"

  # contains clinical data, requires an ehrId from the MPI service
  cdr-service-openehr:
    image: rtweed/qewd-server
    volumes:
      - /ripple-qewd/cdr-service-openehr:/opt/qewd/mapped
      - /ripple-qewd/yottadb/openehr:/root/.yottadb/r1.22_x86_64/g
    ports:
      - "8003:8080"

  ### ETHERCIS ###

  # ethercis-server is the openEHR persistence mechanism for Ripple Stack
  ethercis-server:
    image: pacharanero/ethercis-server-docker
    depends_on:
      - ethercis-db
    ports:
      - "8081:8080"
    volumes:
      - eth-server-logs:/var/opt/ecis/logs
    environment:
      - DB_HOST=ethercis-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres

  # ethercis uses a customised PostgreSQL database internally
  ethercis-db:
    image: pacharanero/ethercis-database-docker
    ports:
      - "5432:5432"
    volumes:
      - eth-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

# data volumes provide persistence. All other containers are ephemeral
volumes:
  eth-data-volume:
  eth-server-logs:
